name: Build and Push Custom Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      # Step 2: Install Dependencies for OpenWrt SDK
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git gettext unzip file libssl-dev wget python3

      # Step 3: Set up OpenWrt SDK
      - name: Setup OpenWrt SDK
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cd ..

      # Step 4: Copy Custom Packages from Source Repo to OpenWrt SDK
      - name: Copy Custom Packages
        run: |
          mkdir -p openwrt-sdk/package/custom
          cp -r ./* openwrt-sdk/package/custom/

      # Step 5: Build Packages for Each Architecture
      - name: Build Packages for Each Architecture
        run: |
          mkdir -p openwrt-sdk
          cp -r ./* openwrt-sdk/
          cd openwrt-sdk
          for arch in $(cat ../architectures.txt); do
            # Load default config for architecture
            make defconfig ARCH=$arch
            # Build the package
            make package/compile ARCH=$arch
            # Ensure IPK files are copied
            mkdir -p ../compiled-packages/$arch
            cp bin/packages/$arch/*.ipk ../compiled-packages/$arch/
          done

      # Step 6: Push Compiled Packages to Target Repository
      - name: Push to Target Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/peditx/passrepo.git target-repo
          cd target-repo
          rm -rf *
          cp -r ../compiled-packages/* .
          git add .
          git commit -m "Update compiled packages"
          git push origin main
