name: Build and Release

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Select the deploy target'
        required: false
        default: 'both'
        type: choice
        options:
          - github
          - sftp
          - both

  push:
    paths:
      - cur_ver.json

jobs:
  generate_matrix:
    name: Set matrix
    runs-on: ubuntu-latest
    outputs:
      sdks: ${{ steps.out.outputs.sdks }}
    strategy:
      matrix:
        ref:
          - main
          - openwrt-21.02
          - openwrt-22.03
          - openwrt-23.05
          - openwrt-24.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: ${{ matrix.ref }}

      - name: Set targets
        id: find_targets
        run: |
          REF=${{ matrix.ref }}

          # sdks
          JSON='['
          FIRST=1

          while read -r line;
          do
            ARCH=$(echo "$line" | cut -d " " -f 1)

            [[ $FIRST -ne 1 ]] && JSON="$JSON"','
            FIRST=0

            JSON="$JSON"'{"arch":"'"$ARCH"'","ref":"'"$REF"'"}'
          done <<< $(perl ./scripts/dump-target-info.pl architectures 2>/dev/null)

          JSON="$JSON"']'
          echo -e "\n---- sdks ----\n"
          echo "$JSON"
          echo -e "\n---- sdks ----\n"
          echo "sdks=$JSON" >> "$GITHUB_OUTPUT"

      - uses: cloudposse/github-action-matrix-outputs-write@main
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.ref }}
          outputs: |-
            sdks: ${{ steps.find_targets.outputs.sdks }}

  gather_matrix:
    name: Gather build matrices
    runs-on: ubuntu-latest
    needs: generate_matrix
    outputs:
      result: ${{ steps.gather.outputs.result }}
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: generate_matrix
      - name: Gather matrices
        id: gather
        run: |
          result=$(jq -c '.sdks[]' <<< '${{ steps.read.outputs.result }}' | jq -c -s add)
          echo "result=${result}" >> $GITHUB_OUTPUT

  release:
    name: Build for ${{ matrix.arch }}-${{ matrix.ref }}
    runs-on: ubuntu-latest
    needs: gather_matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.gather_matrix.outputs.result) }}

    steps:
      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install nvchecker
        run: pip3 install nvchecker

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get build path
        id: get_build_path
        run: |
          REF=${{ matrix.ref }}
          if [[ $REF == openwrt-* ]]; then
            # openwrt-22.03 -> releases/packages-22.03
            VERSION=${REF//openwrt-/}
            pkg=releases/packages-$VERSION
            log=releases/faillogs-$VERSION
          else
            # master -> snapshots/packages
            pkg=snapshots/packages
            log=snapshots/faillogs
          fi
          echo "pkg=$pkg" >> "$GITHUB_OUTPUT"
          echo "log=$log" >> "$GITHUB_OUTPUT"

      - name: Retrieve Version
        id: ver
        run: |
          cp cur_ver.json new_ver.json
          vers=$(nvcmp -c nvchecker.toml -aj)
          jq -cr 'map("\(.name)=\(.newver)") | .[]' <<< $vers >> $GITHUB_OUTPUT

      - name: Override golang version
        if: contains(fromJSON('["openwrt-21.02", "openwrt-22.03", "openwrt-23.05"]'), matrix.ref)
        run: echo "GOLANG_COMMIT=master" >> $GITHUB_ENV

      - name: Build Package
        uses: moetayuko/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.ref }}
          EXTRA_FEEDS: >-
            src-git|passwall_packages|https://github.com/xiaorouji/openwrt-passwall-packages^${{ steps.ver.outputs.packages }}
            src-git|passwall_luci|https://github.com/peditx/openwrt-passwall^${{ steps.ver.outputs.passwall }}
            src-git|passwall2|https://github.com/peditx/openwrt-passwall2^${{ steps.ver.outputs.passwall2 }}
          KEY_BUILD: ${{ secrets.SIGN_PRIV_KEY }}
          V: s
          IGNORE_ERRORS: n m y
          BUILD_LOG: 1

      - name: Finding failure logs
        working-directory: logs/package/feeds
        run: |
          sed -ne 's!^ *ERROR: package/feeds/\(passwall[^ ]*\) .*$!\1!p' ../error.txt | sort -u | xargs -r find > ../../../logs.txt
          cat ../../../logs.txt

      - name: Prepare Output Folder
        run: |
          PKG_DIR=${{ steps.get_build_path.outputs.pkg }}/${{ matrix.arch }}
          LOG_DIR=${{ steps.get_build_path.outputs.log }}/${{ matrix.arch }}
          mkdir -p dist/$PKG_DIR dist/$LOG_DIR

          rsync -av bin/packages/${{ matrix.arch }}/passwall* dist/$PKG_DIR/
          rsync -av --files-from=logs.txt logs/package/feeds/ dist/$LOG_DIR/

      - name: Upload Output Folder
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-passwall-${{ matrix.arch }}-${{ matrix.ref }}
          path: dist/
          retention-days: 7

  deploy:
    concurrency:
      group: deploy
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        worker: [ 'worker1', 'worker2', 'worker3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean up disk space before deploy
        run: sudo rm -rf /usr/share/dotnet & sudo rm -rf /opt/ghc & rm -rf logs/ & find /home/runner/runners/2.321.0/_diag/ -type f -name '*.log' -delete

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: openwrt-passwall-*
          path: dist/
          retention-days: 7

      - name: Add public key
        run: cp passwall.pub dist/

      - name: Conditional Deploy to GitHub
        if: ${{ github.event.inputs.deploy_target == 'github' || github.event.inputs.deploy_target == 'both' }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          BRANCH_NAME="build-output/deploy"
          git checkout -b "$BRANCH_NAME"

          cp -r dist/* .
          git add .
          git commit -m "Add build outputs for $BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Conditional Upload to SFTP
        if: ${{ github.event.inputs.deploy_target == 'sftp' || github.event.inputs.deploy_target == 'both' }}
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          sshpass -p $SFTP_PASSWORD sftp -oBatchMode=no -b - $SFTP_USER@$SFTP_SERVER << !
          mkdir -p /var/www/html/passwall-packages/
          cd /var/www/html/passwall-packages/
          put -r dist/*
          bye
          !
