name: Build OpenWrt Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Pull OpenWrt SDK Docker Image
      - name: Pull OpenWrt SDK Docker Image
        run: |
          docker pull openwrt/sdk:x86_64

      # Step 3: Build Packages inside Docker Container
      - name: Build Packages
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/workspace openwrt/sdk:x86_64 bash -c "
            set -e
            TMP_DIR=\$(mktemp -d -t sdk-XXXXXXXXXX) &&
            echo 'Temporary directory created: \$TMP_DIR' &&
            cd \$TMP_DIR &&
            
            # Clone SDK
            git clone https://github.com/openwrt/openwrt-sdk.git sdk &&
            cd sdk &&
            
            # Add custom packages
            mkdir -p package/custom &&
            cp -r /workspace/your-package-directory/* package/custom/ &&
            
            # Update and install feeds
            ./scripts/feeds update -a &&
            ./scripts/feeds install -a &&
            
            # Build packages for all architectures
            for arch in \$(cat /workspace/architectures.txt); do
              echo 'Building for architecture: \$arch' &&
              make defconfig &&
              make package/compile V=s ARCH=\$arch &&
              mkdir -p /workspace/compiled-packages/\$arch &&
              cp bin/packages/\$arch/*.ipk /workspace/compiled-packages/\$arch/;
            done
          "

      # Step 4: Push Built Packages to Target Repository
      - name: Push to Target Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/peditx/passrepo.git target-repo
          cd target-repo
          rm -rf *
          cp -r ../compiled-packages/* .
          git add .
          git commit -m "Update compiled packages"
          git push origin main
