name: Build OpenWrt Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Pull OpenWrt SDK Docker Image
      - name: Pull OpenWrt SDK Docker Image
        run: |
          docker pull openwrt/sdk:x86_64

      # Step 3: Prepare SDK and Build Packages
      - name: Build Packages
        run: |
          # Create a directory for the OpenWrt SDK
          mkdir -p $GITHUB_WORKSPACE/openwrt-sdk

          # Run Docker container for building packages
          docker run --rm -v $GITHUB_WORKSPACE:/workspace openwrt/sdk:x86_64 bash -c "
            cd /workspace &&
            mkdir -p openwrt-sdk/package/custom &&
            cp -r ./your-package-directory/* openwrt-sdk/package/custom/ &&
            cd openwrt-sdk &&
            ./scripts/feeds update -a &&
            ./scripts/feeds install -a &&
            make defconfig &&
            for arch in \$(cat ../architectures.txt); do
              echo 'Building for architecture: \$arch';
              make package/compile V=s ARCH=\$arch &&
              mkdir -p ../compiled-packages/\$arch &&
              cp bin/packages/\$arch/*.ipk ../compiled-packages/\$arch/;
            done
          "

      # Step 4: Push Built Packages to Target Repository
      - name: Push to Target Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/peditx/passrepo.git target-repo
          cd target-repo
          rm -rf *
          cp -r ../compiled-packages/* .
          git add .
          git commit -m "Update compiled packages"
          git push origin main
