name: Build and Release luci-theme-peditx for Multiple Architectures

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: 
          - aarch64_cortex-a53
          - aarch64_generic
          - ar71xx_generic
          - bcm53xx
          - bmx280
          - brcm47xx
          - ipq40xx
          - mips_24kc
          - mipsel_24kc
          - mips_mips32
          - ppc64le
          - ramips_mt76x8
          - ramips_mt7621
          - x86_64
          - x86_64_gcc-12
          - x86_64-musl
          - x86_64_musl_gcc
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git gettext unzip zlib1g-dev file python3 python3-distutils curl

      - name: Setup OpenWrt SDK for ${{ matrix.architecture }}
        run: |
          ARCH=${{ matrix.architecture }}
          SDK_FILE="openwrt-sdk-22.03.5-${ARCH}_gcc-12.3.0_musl.Linux-x86_64.tar.xz" # updated version
          if [ "$ARCH" == "aarch64_cortex-a53" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/mvebu/cortexa53/$SDK_FILE"
          elif [ "$ARCH" == "aarch64_generic" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/rockchip/armv8/$SDK_FILE"
          elif [ "$ARCH" == "ar71xx_generic" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/ar71xx/generic/$SDK_FILE"
          elif [ "$ARCH" == "bcm53xx" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/bcm53xx/generic/$SDK_FILE"
          elif [ "$ARCH" == "bmx280" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/bmx280/generic/$SDK_FILE"
          elif [ "$ARCH" == "brcm47xx" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/brcm47xx/generic/$SDK_FILE"
          elif [ "$ARCH" == "ipq40xx" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/ipq40xx/generic/$SDK_FILE"
          elif [ "$ARCH" == "mips_24kc" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/ath79/generic/$SDK_FILE"
          elif [ "$ARCH" == "mipsel_24kc" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/ramips/rt288x/$SDK_FILE"
          elif [ "$ARCH" == "mips_mips32" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/bcm63xx/generic/$SDK_FILE"
          elif [ "$ARCH" == "ppc64le" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/ppc64le/generic/$SDK_FILE"
          elif [ "$ARCH" == "ramips_mt76x8" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/ramips/mt76x8/$SDK_FILE"
          elif [ "$ARCH" == "ramips_mt7621" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/ramips/mt7621/$SDK_FILE"
          elif [ "$ARCH" == "x86_64" ]; then
            SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/$SDK_FILE"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi

          # Check if SDK file exists
          echo "Building for architecture: $ARCH"
          wget $SDK_URL
          mkdir -p sdk
          tar -xJf $SDK_FILE -C sdk --strip-components=1
          cd sdk
          echo "src-git packages https://github.com/openwrt/packages.git" > feeds.conf.default
          echo "src-git luci https://github.com/openwrt/luci.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add luci-theme-peditx package
        run: |
          cd sdk/package
          git clone https://github.com/peditx/luci-theme-peditx
          cd ..
          echo "CONFIG_PACKAGE_luci-theme-peditx=m" >> .config

      - name: Build luci-theme-peditx for ${{ matrix.architecture }}
        run: |
          cd sdk
          make defconfig
          make package/luci-theme-peditx/compile -j1 V=sc

      - name: Save luci-theme-peditx package
        run: |
          cd sdk
          mkdir -p artifacts
          find bin/ -name "*.ipk" -exec cp {} artifacts/ \;

      - name: Create Release for ${{ matrix.architecture }}
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.5-${{ matrix.architecture }}
          name: luci-theme-peditx release - ${{ matrix.architecture }} - ${{env.timestamp}}
          body: latest release of luci-theme-peditx theme for OpenWrt on ${{ matrix.architecture }} architecture.
          files: sdk/artifacts/luci-theme-peditx_*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          timestamp: ${{ github.run_id }}
