name: Build and Deploy OpenWrt Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository A
      - name: Checkout Repository A
        uses: actions/checkout@v3

      # Step 2: Define Architectures
      - name: Define Architectures
        run: |
          echo "x86_64 arm_cortex-a9 mipsel_24kc mips_24kc aarch64_generic powerpc_8540" > architectures.txt

      # Step 3: Pull OpenWrt SDK Docker Image
      - name: Pull OpenWrt SDK Docker Image
        run: |
          docker pull openwrt/sdk:x86_64

      # Step 4: Build Packages for All Architectures
      - name: Build Packages
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/workspace \
            openwrt/sdk:x86_64 bash -c "
              set -e
              mkdir -p /workspace/output
              cp -r /workspace/* /sdk/package/custom
              ./scripts/feeds update -a
              ./scripts/feeds install -a
              for arch in \$(cat /workspace/architectures.txt); do
                echo 'Building for architecture: \$arch'
                make defconfig
                make package/compile V=s ARCH=\$arch
                mkdir -p /workspace/output/\$arch
                cp bin/packages/\$arch/*.ipk /workspace/output/\$arch/
              done
            "

      # Step 5: Push Compiled Packages to Repository B
      - name: Push to Repository B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/peditx/passrepo.git passrepo
          cd passrepo
          rm -rf *
          cp -r ../output/* .
          git add .
          git commit -m "Update compiled packages"
          git push origin main
