name: Build and Push Custom Packages with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Pull OpenWrt SDK Docker Image
      - name: Pull OpenWrt SDK Docker Image
        run: |
          docker pull openwrt/sdk:x86-64-23.5.0

      # Step 4: Run OpenWrt SDK inside Docker container
      - name: Run OpenWrt SDK Build in Docker
        run: |
          docker run --rm -v $(pwd):/workspace openwrt/sdk:x86-64-23.5.0 bash -c "
            cd /workspace &&
            mkdir -p openwrt-sdk/package/custom &&
            cp -r ./your-package-directory/* openwrt-sdk/package/custom/ &&
            cd openwrt-sdk &&
            for arch in \$(cat ../architectures.txt); do
              echo 'Building for architecture: \$arch';
              make defconfig ARCH=\$arch &&
              make package/compile ARCH=\$arch &&
              mkdir -p ../compiled-packages/\$arch &&
              cp bin/packages/\$arch/*.ipk ../compiled-packages/\$arch/;
            done
          "

      # Step 5: Push Compiled Packages to Target Repository
      - name: Push to Target Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/peditx/passrepo.git target-repo
          cd target-repo
          rm -rf *
          cp -r ../compiled-packages/* .
          git add .
          git commit -m "Update compiled packages"
          git push origin main
